// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZY3xojfZskfcI8LZkm_1SuNa0x-RCE3o',
    appId: '1:74111648461:web:0f4181ead28d4948e55f84',
    messagingSenderId: '74111648461',
    projectId: 'khidmatai-9f41f',
    authDomain: 'khidmatai-9f41f.firebaseapp.com',
    storageBucket: 'khidmatai-9f41f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_cZjEd9ko7MqcHjOiLWZbja4UkLo0ns',
    appId: '1:74111648461:android:d381ca341a8f9948e55f84',
    messagingSenderId: '74111648461',
    projectId: 'khidmatai-9f41f',
    storageBucket: 'khidmatai-9f41f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBj8rExGVMvSyjt8yvE5XQyknV18BuQc',
    appId: '1:74111648461:ios:aa4e81fdc4e9740be55f84',
    messagingSenderId: '74111648461',
    projectId: 'khidmatai-9f41f',
    storageBucket: 'khidmatai-9f41f.firebasestorage.app',
    iosClientId: '74111648461-89koenjdm682veke3jk3skbkea8913g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ustaadAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXBj8rExGVMvSyjt8yvE5XQyknV18BuQc',
    appId: '1:74111648461:ios:aa4e81fdc4e9740be55f84',
    messagingSenderId: '74111648461',
    projectId: 'khidmatai-9f41f',
    storageBucket: 'khidmatai-9f41f.firebasestorage.app',
    iosClientId: '74111648461-89koenjdm682veke3jk3skbkea8913g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ustaadAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZY3xojfZskfcI8LZkm_1SuNa0x-RCE3o',
    appId: '1:74111648461:web:80542044d8b219ece55f84',
    messagingSenderId: '74111648461',
    projectId: 'khidmatai-9f41f',
    authDomain: 'khidmatai-9f41f.firebaseapp.com',
    storageBucket: 'khidmatai-9f41f.firebasestorage.app',
  );
}
